name: watchsteroids
description: The classic asteroids game on your wrist
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flame: ^1.5.0
  flame_bloc: ^1.8.1
  flame_svg: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  nested: ^1.0.0
  path_provider: ^2.0.11
  wearable_rotary: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_icons: