name: watchsteroids
description: The classic asteroids game on your wrist
version: 0.0.2+5
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flame: ^1.9.1
  flame_bloc: ^1.11.0
  flame_svg: ^1.7.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  nested: ^1.0.0
  path_provider: ^2.1.1
  wearable_rotary: ^2.0.2

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/images/
    - shorebird.yaml

flutter_icons: